//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Score.
        /// </summary>
        public static string Export_StudentResults_AverageScore {
            get {
                return ResourceManager.GetString("Export_StudentResults_AverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Sessions.
        /// </summary>
        public static string Export_StudentResults_CompletedSessions {
            get {
                return ResourceManager.GetString("Export_StudentResults_CompletedSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Export_StudentResults_Course {
            get {
                return ResourceManager.GetString("Export_StudentResults_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Session.
        /// </summary>
        public static string Export_StudentResults_CurrentSession {
            get {
                return ResourceManager.GetString("Export_StudentResults_CurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Export_StudentResults_Grade {
            get {
                return ResourceManager.GetString("Export_StudentResults_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Export_StudentResults_Level {
            get {
                return ResourceManager.GetString("Export_StudentResults_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string Export_StudentResults_Level_0 {
            get {
                return ResourceManager.GetString("Export_StudentResults_Level_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practise.
        /// </summary>
        public static string Export_StudentResults_Level_1 {
            get {
                return ResourceManager.GetString("Export_StudentResults_Level_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revise.
        /// </summary>
        public static string Export_StudentResults_Level_2 {
            get {
                return ResourceManager.GetString("Export_StudentResults_Level_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revise Again.
        /// </summary>
        public static string Export_StudentResults_Level_3 {
            get {
                return ResourceManager.GetString("Export_StudentResults_Level_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Export_StudentResults_Session {
            get {
                return ResourceManager.GetString("Export_StudentResults_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Export_StudentResults_Stage {
            get {
                return ResourceManager.GetString("Export_StudentResults_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string Export_StudentResults_StudentName {
            get {
                return ResourceManager.GetString("Export_StudentResults_StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Export_StudentResults_SummaryTitle {
            get {
                return ResourceManager.GetString("Export_StudentResults_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Analysis.
        /// </summary>
        public static string Export_StudentResults_Title {
            get {
                return ResourceManager.GetString("Export_StudentResults_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Key.
        /// </summary>
        public static string Export_StudentsInfo_GroupKey {
            get {
                return ResourceManager.GetString("Export_StudentsInfo_GroupKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Export_StudentsInfo_GroupName {
            get {
                return ResourceManager.GetString("Export_StudentsInfo_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Export_StudentsInfo_Password {
            get {
                return ResourceManager.GetString("Export_StudentsInfo_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string Export_StudentsInfo_StudentName {
            get {
                return ResourceManager.GetString("Export_StudentsInfo_StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students list.
        /// </summary>
        public static string Export_StudentsInfo_Title {
            get {
                return ResourceManager.GetString("Export_StudentsInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Export_StudentsInfo_User {
            get {
                return ResourceManager.GetString("Export_StudentsInfo_User", resourceCulture);
            }
        }
    }
}
